// TYPE ACTION OF MODAL
export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'

// TYPE ACTION OF SIDEBAR
export const SIDEBAR_ACTION_CLOSE = 'SIDEBAR_ACTION_CLOSE'
export const SIDEBAR_ACTION_OPEN = 'SIDEBAR_ACTION_OPEN'
