// TYPE ACTION OF MODAL
export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'

// TYPE ACTION OF SIDEBAR
export const SIDEBAR_ACTION_CLOSE = 'SIDEBAR_ACTION_CLOSE'
export const SIDEBAR_ACTION_OPEN = 'SIDEBAR_ACTION_OPEN'

// DEFAULT MAPBOX LOCATION
export const DEFAULT_MAPBOX_LOCATION = {
  latitude: 16.06045710530602,
  longitude: 108.2097851153426,
  zoom: 15
}
